name: "Astro Deploy"
description: "A composite action that prepares your Astro site to be deployed to GitHub Pages"
inputs:
  path:
    description: "Path of the directory containing your site"
    required: false
    default: ""
  node-version:
    description: "The node version to use"
    required: false
    default: "16"
  package-manager:
    description: "If not automatically detectable, you may specify your preferred package manager"
    required: false
    default: ""
outputs:
  package-manager:
    description: "detected package manager"
    value: ${{ steps.lockfile.outputs.package-manager }}

runs:
  using: composite
  steps:
    - name: Check lockfiles
      id: lockfile
      shell: "bash"
      env:
        INPUT_PM: ${{ inputs.package-manager }}
      run: |
        len=`echo $INPUT_PM | wc -c`
        if [ $len -gt 1 ]; then
            echo "'::set-output name=package-manager::$INPUT_PM'"
        elif [ $(find "." -name "pnpm-lock.yaml") ]; then 
            echo "'::set-output name=package-manager::pnpm'"
        elif [ $(find "." -name "yarn.lock") ]; then 
            echo "'::set-output name=package-manager::yarn'"
        elif [ $(find "." -name "package-lock.json") ]; then 
            echo "'::set-output name=package-manager::npm'"
        else
            echo "No lockfile found.
        Please specify your preferred \"package-manager\" in the action configuration."
            exit 1
        fi

    - name: Setup PNPM
      if: ${{ outputs.package-manager.value == 'pnpm' }}
      uses: pnpm/action-setup@v2.2.2

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        cache: ${{ outputs.package-manager.value }}

    - name: Install
      shell: "bash"
      run: ${{ outputs.package-manager.value }} install

    - name: Build
      shell: "bash"
      run: ${{ outputs.package-manager.value }} run build

    - name: Upload Pages Artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: "${{ inputs.path }}dist/"
